#!/bin/bash
client_root=$(dirname $0:A)
pushd $client_root

export LD_LIBRARY_PATH=lib/linux

linked_libs="-lsocketio -lboost_system -lboost_thread -lfreenect2 -lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_aruco -lopencv_imgproc -lopencv_calib3d -lpthread"
incs="-Iinclude"
out="bin/client"
src="src/client.cpp src/camera.cpp src/calibration.cpp"

g++ -g $incs -L$LD_LIBRARY_PATH -std=c++14 -o $out $src\
    -Wl,-rpath=../$LD_LIBRARY_PATH $linked_libs

popd

