#!/bin/zsh

if [ $# -eq 0 ] ; then
    echo "Needs to supply freenect path!"
    return
fi

if ! [ -d $1 ] ; then
    echo "Freenect path supplied is not a directory"
    return
fi

freenect_path=$1:A

client_root=$(dirname $0:A)

cp -R $freenect_path/include/libfreenect2 $client_root/include/
cp -R $freenect_path/build/libfreenect2 $client_root/include/

cp -R $freenect_path/build/lib/* $client_root/lib/mac

